name: seify_app
description: "سیفی مارکت یکی از بزرگترین فروشگاههای آنلاین ایران در زمینه فروش لوله های فولادی، اتصالات، شیرآلات و انواع آهن آلات"
publish_to: 'none'

version: 1.6.24

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  html: ^0.15.4
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  mailer: ^6.0.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  lottie: ^3.1.2
  package_info_plus: ^9.0.0
  flutter_dotenv: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
 
  assets:
    - assets/img/gallery/fitting/
    - assets/img/gallery/galvanized/
    - assets/img/gallery/gas/
    - assets/img/gallery/mannesmann/
    - assets/img/gallery/scaffold/
    - assets/img/gallery/spiral/
    - assets/img/banner/
    - assets/img/logo/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
